### ISSUE TITLE
Open to contributors for 3.0 release?

### ISSUE THREAD

**Issue by gstro** [thoughtbot/Swish#114]
Hi all. I'm looking forward to using Swish 3.0 for the `Codable` stuff. Are there tasks that I could help out with to move this to an official 3.0 release? I'm using this via CocoaPods and I'd rather not point at master.

**Comment by sidraval** [comment]
We've had this sitting as a draft release for a couple weeks now - consider opening this issue your first contribution 👍 https://github.com/thoughtbot/Swish/releases/tag/v3.0.0

**Comment by gstro** [comment]
Nice! Thanks @sidraval.
