### ISSUE TITLE
Errors on 2.0.3 with Xcode 9.3

### ISSUE THREAD

**Issue by gstro** [thoughtbot/Swish#118]
One of my projects is using Swish 2.0.3. I updated Xcode to 9.3 and I started to see a couple errors. It would be great to get a quick fix for Swish 2.0 out if possible. Unfortunately, we're not able to migrate to Swish 3.0 at this time. Here are the errors I'm seeing:
```
Swish/Source/Models/APIClient.swift:10:108: Struct 'JSONDeserializer' is internal and cannot be referenced from a default argument value
```
(can't use internal type in default arg)

and
```
Swish/Source/Protocols/Request.swift:29:21: Missing argument for parameter #1 in call
```
(needs another`()` inside `.success()`)

I've forked and branched from what looked like a good point for 2.0: 4c9233c. I don't want to open a PR onto master here -- is there a good branch I could PR with these updates? My changes are here:
https://github.com/gstro/Swish/tree/2.0-fixes . Could there be a 2.x release branch? Would love to have this updated on CocoaPods soon too.

**Comment by gfontenot** [comment]
Hey @gstro, sorry for the delay on this. I definitely want to fix this, but want to make sure we do it in the right way. The `.success()` -> `.success(())` change in particular is a source-incompatible change and so needs to be handled in a way that ensures that users upgrading from 2.0.3 don't get hit with errors. The changes should be simple, basically need to do a Swift version check around that line and omit the empty tuple if we're on... I want to say 3.2<. I'll take a run at this as soon as I can.

**Comment by gstro** [comment]
Sounds good to me. Let me know if I can help in some way.

**Comment by gfontenot** [comment]
@gstro How are you pulling in Swish? I'm not seeing the `.success(())` error locally in 9.3 😕

**Comment by gstro** [comment]
I used CocoaPods. I just confirmed this issue with
- New "Single View App" iOS project
- Create a `Podfile` with Swish 2.0 below:
```ruby
target 'SwishTest' do
  use_frameworks!
  pod 'Swish', '~> 2.0'
end
```
- Run `pod install`
- Open the `.xcworkspace` file
- Build

This gives me the two errors I mentioned in the first post of this thread (internal JSONDeserializer, and missing `()` argument). Hope this helps.

**Comment by gfontenot** [comment]
Cool, that's what I assumed you were doing but wanted to confirm. Interesting that the missing `()` error doesn't show up when compiling the project directly in xcode...

**Comment by gfontenot** [comment]
@gstro if you have a min to test against `gfontenot/2.0-fixes` and confirm that it fixes your issues, I'll merge that PR and get a release up asap.

**Comment by gfontenot** [comment]
Actually I pushed 2.0.4 to CocoaPods. You should be able to update and it should fix your issues.

**Comment by gstro** [comment]
Confirmed fixed! Thanks for that quick turnaround.
