### ISSUE TITLE
Swift.DecodingError on success 200 with empty body

### ISSUE THREAD

**Issue by martias** [thoughtbot/Swish#125]
When performing a POST request with an optional `typealias ResponseObject = SendResponse?` a `decodingError` is returned for a response with code 200 and empty body which should be the success response. 
The "SendResponse" JSON content is returned only when the server wants to inform an error.

**Comment by sidraval** [comment]
Thanks for the report, @martias! I'll have some time to look into this tomorrow.

**Comment by sidraval** [comment]
@martias This should be fixed on `master` – not quite sure when we'll get a new release out, but it shouldn't be too long!

**Comment by martias** [comment]
Thanks for the fix @sidraval . We can use it form from the commit hash until a new version is released! 🙂

**Comment by martias** [comment]
Are you planning on doing a new release soon?
