### ISSUE TITLE
Why Swish?

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Swish#16]
I know that this project is still under development but I'd love to know some of the goals / guiding principles, and why someone might prefer Swish over one of the other networking libraries available.

Keep  up the great work :+1:

**Comment by gfontenot** [comment]
Great question. This is something I'll end up bringing into fuller documentation in the future.

Basically, the guiding idea is that the objects touching the network should be the dumbest possible pipes, and should be completely API agnostic. Adding logic or configuration at that level leads to poor testability, and even poorer reusability.

Instead, if we treat the requests themselves as value objects that contain all of the needed configuration, then we can actually set up test suites that are able to describe the API endpoints themselves. If the server expectations change, we change the tests, which shows what we need to add to the requests themselves.

Requests are (typically) dumb value objects that know how to build a request for a specific endpoint, and how to parse the response for this endpoint. Keeping these objects simple means they are _incredibly_ testable without the need to stub out the network at all. Simply passing JSON into the parser and making assertions on the result, or making assertions on the built `NSURLSession` make testing insanely straightforward.

We're also trying to take a more protocol-oriented approach. We're supplying default objects, but our protocols are so general that this library is really more flexible than it would seem on the surface. With some slight modifications, this library could potentially support _any_ system that needs to make "requests" and get back "results" (for example, CoreData isn't too far off).

Finally, we want Swish itself to be as light as possible. I very much dislike working with libraries that try to be all in one solutions, and don't think they ever work well. Instead, Swish is a thin wrapper around gluing together NSURLSession, Argo, and Result.

**Comment by paulyoung** [comment]
Sounds great.

**Comment by paulyoung** [comment]
@gfontenot if you wouldn't mind, could you provide or point me to a small example of what you described? Essentially a very basic client and one or two tests?

The test suite here has been insightful but those are testing Swish and not a potential consumer of it, and the fakes are, well... a bit fake.

**Comment by gfontenot** [comment]
For sure. I tossed up [parts of my current client's test suite in a gist](https://gist.github.com/gfontenot/81187d9e45a1f65aa6dd). It's a simple request that uses the default `parse` implementations so it doesn't test that, but those tests are fairly trivial (send in `JSON`, make assertions on the returned object).

I also included some of the shared example stuff that we're using so that you can see some of the extra architecture around this stuff. I want to extract at least _some_ of this to a companion framework for testing network stacks using Swish.

**Comment by paulyoung** [comment]
Thanks @gfontenot. I took some inspiration from that and created https://github.com/the-grid/Disc

**Comment by gfontenot** [comment]
That's awesome. I'd love to hear your thoughts about what you think works/doesn't work, things that could be extracted, etc.

**Comment by paulyoung** [comment]
Definitely will. Here's a bit of info for now:

I completely abstracted Swish as can be seen here: https://github.com/the-grid/Disc/blob/7eb2a26c26b7c6402827d46e1ec6c2adb9876222/Disc/Networking/APIClient.swift

I then basically used the pattern here (private request and public method) for each endpoint: https://github.com/the-grid/Disc/blob/7eb2a26c26b7c6402827d46e1ec6c2adb9876222/Disc/Networking/Resources/User/Identity/GetIdentities.swift

I also really wanted to try and only test the public API, not relying on `@testable` or exposing anything purely for testing. I used [Mockingjay](https://github.com/kylef/Mockingjay) to stub out API responses which worked pretty well.

The tests pretty much followed this format: https://github.com/the-grid/Disc/blob/7eb2a26c26b7c6402827d46e1ec6c2adb9876222/DiscTests/Networking/User/GitHubToken/GetPublicGitHubTokenSpec.swift

I think this approach left me feeling a bit conflicted in that `Request`s have become really easy to test, but my initial goal of not leaking any implementation details meant that I didn't want to expose them or test them directly.

This may change but that's where it's at right now.

**Comment by paulyoung** [comment]
Forgot to say, the effortless conversion from `response` (to `JSON` to `Decoded`) to `Result` was a huge win IMO.

**Comment by paulyoung** [comment]
While it's fresh in my memory – in my approach, when tests were failing the error description wasn't super easy to surface.

This is why I'm also expecting it `to(beNil())`, but I still need to visually dig through the entire `userInfo` object for the description.

**Comment by gfontenot** [comment]
Thanks for the feedback, @paulyoung. I really dig your abstractions. Nice stuff. We've pulled that same `baseRequest` function into a few different apps now. I wonder if there's a nice way to abstract that.

**Comment by paulyoung** [comment]
In case this influences that in any way, there's some updated usage since we had to deal with the requirements for several different OAuth providers.

[Networking/Resources/User/Identity/AddIdentity.swift](https://github.com/the-grid/Disc/blob/c62d7b576f88e02e41081845494ec781008b9a5b/Disc/Networking/Resources/User/Identity/AddIdentity.swift) and [Networking/Helpers/Request.swift](https://github.com/the-grid/Disc/blob/c62d7b576f88e02e41081845494ec781008b9a5b/Disc/Networking/Helpers/Request.swift) are probably the most relevant.

**Comment by gfontenot** [comment]
I'm going to close this for now.
