### ISSUE TITLE
Make NetworkRequestPerformer public

### ISSUE THREAD

**Issue by jakecraige** [thoughtbot/Swish#19]
In an app I'm working on I'd love to subclass this and still be able to call the default implementation. Since it's not exposed I'm unable to do that. 

Happy to open a PR if this is something y'all think would be beneficial.

**Comment by paulyoung** [comment]
@jakecraige `NetworkRequestPerformer` is a struct which doesn't support subclassing but even if it did, I would have suggested creating your own type that wraps it. 

Would that work for you?

**Comment by jakecraige** [comment]
Good catch! I didn't notice that. 

The making it public point sill applies though correct? If I want to wrap it I first need access :)

**Comment by paulyoung** [comment]
Could you wrap `APIClient` instead?

**Comment by gfontenot** [comment]
There's no real reason for this type to be private, so I'd be :+1: if you want to open a PR.
