### ISSUE TITLE
JSON payload helpers don't accept top level arrays

### ISSUE THREAD

**Issue by sidraval** [thoughtbot/Swish#35]
The `jsonPayload` `NSURLRequest` extensions have type `NSDictionary`, but top level arrays are valid JSON too.

I'd love to use Argo's `JSON` type, but there are two problems:
- Can't go from `JSON` to something accepted by `NSJSONSerialization.dataWithJSONObject`
- Can't provide `override var jsonPayload` for `NSMutableURLRequest`, because `override var` only works in extensions if the return type is Objective C compatible.

We could use a custom `JSONPayload`, and define it only on `NSMutableURLRequest`, but this seems sub optimal...

**Comment by gilesvangruisen** [comment]
@sidraval what's your current workaround for this?

**Comment by sidraval** [comment]
https://github.com/thoughtbot/Swish/tree/sr-top-level-arrays

**Comment by sidraval** [comment]
Damian and I were working on this, and came up with: https://github.com/thoughtbot/Swish/commit/a56452b52d84d984f5a6b207be1ce2b24ada5b41

While `AnyObject?` isn't ideal, our thoughts are that once the end user sets `.jsonPayload = ...`, they probably won't have a reason to fetch/manipulate it afterward.

Another solution we considered was a `SwishRequest`, that contained both the `NSMutableURLRequest` and a `JSONPayload` enum that had cases for arrays and dictionaries. This added a lot of overhead in code in exchange for no gain, as far as we could tell.

Thoughts? cc @thoughtbot/ios @paulyoung

**Comment by gfontenot** [comment]
@sidraval can you open a PR so we can discuss there?

**Comment by sidraval** [comment]
:+1: https://github.com/thoughtbot/Swish/pull/59

**Comment by sidraval** [comment]
Closing, as #59 is merged.
