### ISSUE TITLE
Add the ability to model errors as well as successes

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Swish#46]
It'd be nice to be able to model error states if you know what they look like. It'd be really nice to bake that into the API in a way that lets us do that cleanly. We can probably do this by providing a `ResponseError` typealias alongside `ResponseType` and adding a `parseError` function to `Request`.

We'd want to maintain compatibility with the current API (mainly for simplicity), so we should default the error to `NSError` and add a default implementation for `ResponseError` that behaves like #40

Only concern would be: What happens if `parseError` fails? Should it be able to? How do people recover from an Argo parsing failure? Do we care?

**Comment by kaishin** [comment]
> Only concern would be: What happens if parseError fails? Should it be able to? How do people recover from an Argo parsing failure? Do we care?

Given `ResponseSuccessType` and `ResponseErrorType` I can see this going one of 2 ways:

``` swift
  func parse(j: JSON) -> Result< ResponseSuccessType, NSError>
  func parseError(j: JSON) -> Result< ResponseErrorType, NSError>
```

or

``` swift
func parse(j: JSON) throws -> Result<ResponseSuccessType, ResponseErrorType>
```

In both cases you'd get a parsing error if parsing both types fails. I understand that backward compatibility is a priority so the first is more in-line with the current API.
