### ISSUE TITLE
JSON Decoding errors should be from the Swish domain

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Swish#48]
Right now, we're using `Result`'s error constructor when transforming from `Decoded` -> `Result`. This isn't a big deal, but it might be clearer to use `Swish`'s constructor for consistency.

**Comment by paulyoung** [comment]
Makes sense. I didn't realize that this didn't happen as part of #40.

I wonder if it would be simple enough to support custom error type so that consumers of API clients backed by Swish see a "MyApiClient" related error instead of something they won't recognize like "Swish".
