### ISSUE TITLE
Support query string encoding

### ISSUE THREAD

**Issue by jakecraige** [thoughtbot/Swish#49]

**Comment by paulyoung** [comment]
I'm doing this here in case it's of any use: https://github.com/the-grid/Disc/blob/0.2.1/Disc/Networking/Helpers/Request.swift#L6-L19

**Comment by jakecraige** [comment]
Looks like iOS actually provides a nice way to do this now https://littlebitesofcocoa.com/128-nsurlqueryitem-nsurlcomponents?utm_source=Little+Bites+of+Cocoa&utm_campaign=2598619d3c-005_watch_screenshot_magic5_21_2015&utm_medium=email&utm_term=0_2b6df83b4b-2598619d3c-111012021

**Comment by paulyoung** [comment]
Yep, that's what I used.

I just mapped from `[String: String]` and then sorted by key because unit tests were failing (only when running from the command line) due to different ordering.

I don't remember why I checked for empty query items but it was probably to prevent a redundant trailing `?`.

**Comment by jakecraige** [comment]
hahaha I didn't actually get around to reading that snippet yet, my bad. I was just brain dumping that link here since I just read about it.

**Comment by gfontenot** [comment]
Given that, I'm going to close this.
