### ISSUE TITLE
Maybe use Deferred instead of just completion blocks?

### ISSUE THREAD

**Issue by sgoodwin** [thoughtbot/Swish#57]
I was thinking it might be useful for using a Deferred monad instead of supplying completion blocks. These could be `Deferred<Result<T>>`'s which allow for communicating errors nicely as well. This would allow us to use bind and map to link additional processing steps to the completion of a request easily and use convenient functions like `any`, `all`, or `first` for when we need to combine multiple http requests in your app. We would also have the convenience function `upon` that would allow for the similar convenient callback-based handling as before. So instead of `performRequest(request) { some block code here }` you would have `performRequest(request).upon { some block code here }` which seems nice still I think.

This issue is just to discuss wether this would be useful or nice to have.

**Comment by gfontenot** [comment]
I think this makes total sense. That being said, I'm hesitant to add it to the default API. I'm not thrilled about adding another dependency to the project, and I'd also hate to lock us into one specific `Deferred` lib over any other. I believe this would _also_ make it more difficult for us to wrap Swish in RAC or RxSwift, which is what we've done a few times in client projects.

**Comment by sgoodwin** [comment]
makes sense
