### ISSUE TITLE
Contribute beVoid() matcher to Nimble?

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Swish#58]
I've found myself using [`beVoid()`](https://github.com/thoughtbot/Swish/blob/77abc99d6f957307da88544e7db089544d4127f7/Tests/Helpers/NimbleMatchers.swift#L4-L14) in projects that don't use Swish, so wanted to propose that this be added to Nimble.

cc @jeffh

**Comment by gfontenot** [comment]
I like this idea a lot. We actually wrote a number of matchers that actually _aren't_ specific to Swish at all that would be nice to extract in some manner.

**Comment by jeffh** [comment]
Sounds good to me! Send a PR to the Nimble project. :+1:

**Comment by sidraval** [comment]
https://github.com/Quick/Nimble/pull/250
