### ISSUE TITLE
New logo + Commit issues

### ISSUE THREAD

**Issue by whmii** [thoughtbot/Swish#60]
@sidraval  So I attempted to use Github's new File upload to PR feature and it instead decided It would just commit directly to master :/ 

Sorry about that. :bow: Might be worth rolling back.

Anywho~! New Logo! :heart: :heart_eyes: JPG is in the root dir but there's probably a better place for it. I have an SVG version as well. :+1: 

![swish-logo-v4](https://cloud.githubusercontent.com/assets/2489247/13209558/2f656d86-d8f3-11e5-8b86-438cf6491a77.jpg)

**Comment by sidraval** [comment]
No worries! https://github.com/thoughtbot/Swish/pull/61 Fixes stuff. I've moved the logo to the `gh-pages` branch.

Nice work :)

**Comment by whmii** [comment]
An alternate that is a little too crazy but sure would look good on a t-shirt :D
![screen shot 2016-02-22 at 11 24 44 am](https://cloud.githubusercontent.com/assets/2489247/13235513/47be7780-d98c-11e5-91ba-7fabf1b6f683.png)

**Comment by whmii** [comment]
Here is the codepen for feedback on this design https://redpen.io/ym97c0cf956ff5158e
