### ISSUE TITLE
Allow form style HTTP request bodies

### ISSUE THREAD

**Issue by sidraval** [thoughtbot/Swish#63]
Some APIs want POST bodies as form style, base64 encoded strings, i.e. `key1=value1&key2=value2` instead of JSON. Maybe we should have a way to convert a `[String: AnyObject]` dictionary into form-style bodies?

**Comment by paulyoung** [comment]
I think my comments in #49 apply here too, in case that's of any help in implementing this.

**Comment by sidraval** [comment]
Thanks @paulyoung !

Work is in progress here https://github.com/thoughtbot/Swish/tree/sr-form-style-payloads

**Comment by sidraval** [comment]
#64
