### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by nickvelloff** [thoughtbot/Swish#72]
Hi. I inherited a project that utilizes this awesome library, but I'm super new to it.
I updated the dependencies to support Swift 2.2 and am now receiving a `Segmentation fault: 11` and I can't quite find the issue.

Looking through the change logs here I have a feeling it has something to do with the result error type `Result<AccessToken, NSError>` and `SwishError` (and not using it properly)... but I'm not sure. 

I tries a few different approaches but am hitting a wall.

This is the first file to fail, and the others like it fail to compile for the same reason.
https://github.com/the-grid/Disc/blob/redirect_uri_email/Disc/Networking/Authorization/GetAccessToken.swift

If you have a moment, does anything shout out at you as something I should look at?

Thanks for the work on this library.

**Comment by sidraval** [comment]
The `performRequest` method expects the callback to have type: `Result<T.ResponseObject, SwishError> -> Void`, have you tried changing your callbacks to use `SwishError` instead of `NSError`?

https://github.com/thoughtbot/Swish/blob/master/Source/Models/APIClient.swift#L14

**Comment by gfontenot** [comment]
Yeah, try what @sidraval said. We saw this same thing here and that fixed the segfaults. Other errors _should_ present themselves as proper compilation errors once you've fixed that.

**Comment by nickvelloff** [comment]
Actually I did try that, but let me give it another shot. Thanks, let's see what happens.

**Comment by nickvelloff** [comment]
OK so I changed over to `SwishError` and still am stuck on the seg fault. Anything else stand out?

https://github.com/the-grid/Disc/blob/redirect_uri_email/Disc/Networking/Authorization/GetAccessToken.swift

**Comment by nickvelloff** [comment]
FWIW when I roll back to 2d485a7fd411bb92dc5cad2a550508574d3aebbf it compiles (with associated warnings due to Swift)

**Comment by gfontenot** [comment]
We changed this to `ResponseObject`: https://github.com/the-grid/Disc/blob/redirect_uri_email/Disc/Networking/Authorization/GetAccessToken.swift#L5

**Comment by nickvelloff** [comment]
@gfontenot That did it! Thanks so much for taking time to look, you saved me a **lot** of searching. 🙇

**Comment by gfontenot** [comment]
Sorry that we don't have proper versioning yet and also sorry that Swift's compiler wasn't being super helpful. Any feedback you have on the lib is greatly appreciated!

**Comment by nickvelloff** [comment]
Definitely. I really love how _hands off_ this library is. I will certainly have more feedback as I go. It would be great to migrate to this in the "parent" project at some point.
