### ISSUE TITLE
Responses that are not JSON

### ISSUE THREAD

**Issue by nickvelloff** [thoughtbot/Swish#74]
I have what might be a really silly question...
The client that I'm working on until this point only queried endpoints that return `JSON`, and as it turns out I need a route on the API that just returns response codes and a string.

I have tried a few things and not been able to quite figure out how to handle an HTTP response that is not `JSON`, and I know this library is oriented toward `JSON` responses. Seems everything I have tried get's pushed down a path of trying to be parsed, which could just be an oversight on my part for sure.

Is there a clean approach to a non-`JSON` http response?

**Comment by nickvelloff** [comment]
OK I feel a bit less silly in my failed attempts after seeing this https://github.com/thoughtbot/Swish/pull/62
😄

**Comment by sidraval** [comment]
@nickvelloff That PR has been merged into master now 😄  There's a PR now #75 that should have some info about implementing some of the new protocols to be able to parse non JSON.

If you try it, let us know how it goes! Would love feedback.

**Comment by nickvelloff** [comment]
@sidraval I actually forked it play around and got it working with the pr after pulling from master to resolve conflicting dependencies shared in other projects. Works well though I'm not sure my custom deserializer is 100% sound. I based or off the JSON default.  

If there is any way you could do an example of a basic deserializer for the common use case string response the way you would do it so I can do a sanity check. 
Though it works, I'm not sure my implementation is great.

**Comment by nickvelloff** [comment]
FWIW, here is how I did it for better or worse 😄 
https://github.com/the-grid/Disc/blob/master/Disc/Networking/Authorization/RequestEmailLogin.swift
https://github.com/the-grid/Disc/blob/master/Disc/Networking/Helpers/StringDeserializer.swift

**Comment by nickvelloff** [comment]
Oh and here I just added another static `Swish.APIClient` initialized with my custom `StringDeserializer` 
https://github.com/the-grid/Disc/blob/master/Disc/Networking/APIClient.swift

**Comment by sidraval** [comment]
@nickvelloff I juuuust wrote some docs covering exactly that case! https://github.com/thoughtbot/Swish/blob/sr-docs/Documentation/Advanced.md

I think I made some small changes to that PR after you forked it, so the version that ended up getting into master is _slightly_ different from the one you forked.

Feel free to comment on #75 if the docs are unclear.

**Comment by nickvelloff** [comment]
Oh ill be nuking the fork and switching back to master for sure. Thanks for the example @sidraval !!
