### ISSUE TITLE
CocoaPods please!

### ISSUE THREAD

**Issue by lfarah** [thoughtbot/Swish#83]
I'd be cool to also add CocoaPods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by jeroenleenarts** [comment]
Listen to this podcast and you will know why there is not Carthage and CocoaPods integration. It's a deliberate choice.

https://overcast.fm/+F7xlmp_-w/33:18

**Comment by jeroenleenarts** [comment]
https://cocoapods.org/pods/Swish

**Comment by lfarah** [comment]
Awesome! 😄
